import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      // PingFlow "Serene" brand palette (teal + peach), used by the auth pages.
      colors: {
        teal: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
        },
        peach: {
          50: "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
        },
        error: "#ba1a1a",
        "inverse-surface": "#1e293b",
        "tertiary-fixed-dim": "#fed7aa",
        "on-secondary-fixed": "#431407",
        "on-surface-variant": "#64748b",
        "on-tertiary-fixed-variant": "#9a3412",
        "on-primary-container": "#0369a1",
        "on-surface": "#0f172a",
        "surface-container-high": "#e2e8f0",
        "outline-variant": "#cbd5e1",
        "on-error-container": "#93000a",
        primary: "#0284c7",
        "surface-container-low": "#f1f5f9",
        "inverse-primary": "#bae6fd",
        "primary-fixed": "#e0f2fe",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#7c2d12",
        tertiary: "#ea580c",
        "secondary-container": "#ffedd5",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        background: "#f8fafc",
        "surface-variant": "#e0f2fe",
        "surface-dim": "#e2e8f0",
        "on-primary-fixed": "#075985",
        "on-background": "#0f172a",
        "surface-container-highest": "#e2e8f0",
        "on-secondary-fixed-variant": "#c2410c",
        "inverse-on-surface": "#f8fafc",
        "surface-container": "#f8fafc",
        "primary-fixed-dim": "#7dd3fc",
        outline: "#94a3b8",
        "on-secondary-container": "#9a3412",
        surface: "#f8fafc",
        "tertiary-container": "#ffedd5",
        "secondary-fixed": "#ffedd5",
        "primary-container": "#0ea5e9",
        "secondary-fixed-dim": "#fed7aa",
        "surface-bright": "#f8fafc",
        "on-primary-fixed-variant": "#0369a1",
        "tertiary-fixed": "#ffedd5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        display: ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["JetBrains Mono"],
        "body-lg": ["Plus Jakarta Sans"],
        "button-text": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        display: ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "button-text": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        // Custom branded theme — a WhatsApp-inspired emerald/teal palette.
        wa: {
          primary: "#16a34a",
          "primary-content": "#ffffff",
          secondary: "#0ea5e9",
          accent: "#8b5cf6",
          neutral: "#1f2937",
          "base-100": "#ffffff",
          "base-200": "#f4f6f9",
          "base-300": "#e5e9f0",
          "base-content": "#1a2233",
          info: "#0ea5e9",
          success: "#16a34a",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.6rem",
        },
      },
      "light",
      "dark",
    ],
  },
};

export default config;
