import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      // PingFlow "Serene" brand palette (teal + peach), used by the auth pages.
      colors: {
        teal: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
        },
        peach: {
          50: "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
        },
        // Brand teal scale used by the flow builder (matches the mockup).
        brand: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          900: "#134e4a",
        },
        // Material 3 tokens — used by the PingFlow dashboard (chatbots page).
        // `error` stays #ba1a1a so the auth pages' text-error is unchanged.
        "primary-container": "#008378",
        "on-secondary-container": "#5c2400",
        "surface-container-high": "#dce9ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb690",
        primary: "#00685f",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        "tertiary-fixed": "#cce5ff",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        surface: "#f8f9ff",
        "on-primary-container": "#f4fffc",
        "on-secondary-fixed-variant": "#783200",
        "on-primary-fixed": "#00201d",
        background: "#f8f9ff",
        "tertiary-fixed-dim": "#93ccff",
        "secondary-container": "#fd761a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbca",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001d31",
        "on-secondary-fixed": "#341100",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "tertiary-container": "#007bb9",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        outline: "#6d7a77",
        "surface-tint": "#006a61",
        tertiary: "#006194",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "inverse-primary": "#6bd8cb",
        secondary: "#9d4300",
        "outline-variant": "#bcc9c6",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#6bd8cb",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#3d4947",
        "on-tertiary-fixed-variant": "#004b73",
        "primary-fixed": "#89f5e7",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#005049",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        // Custom branded theme — a WhatsApp-inspired emerald/teal palette.
        wa: {
          primary: "#16a34a",
          "primary-content": "#ffffff",
          secondary: "#0ea5e9",
          accent: "#8b5cf6",
          neutral: "#1f2937",
          "base-100": "#ffffff",
          "base-200": "#f4f6f9",
          "base-300": "#e5e9f0",
          "base-content": "#1a2233",
          info: "#0ea5e9",
          success: "#16a34a",
          warning: "#f59e0b",
          error: "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.6rem",
        },
      },
      "light",
      "dark",
    ],
  },
};

export default config;
